apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kind-go-service-config.yml
- ../../base/go-service-pod/
patchesStrategicMerge:
- ./kind-go-service-patch.yml
images:
- name: go-service-image
  newName: ghcr.io/taraktikos/go-service-amd64
  newTag: 5b37aa0
