version: '3.7'
services:
  backend:
    image: ghcr.io/taraktikos/go-service:latest
    container_name: backend
    restart: always
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - /data:/usr/src/app/data
    environment:
      - GO_SERVICE_WEB_SSL_ENABLED=true
      - GO_SERVICE_WEB_SSL_FQDN=new.bankets.com.ua
      - GO_SERVICE_DB_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/go-service
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine3.14
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: go-service
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
