version: '3.9'
services:
  backend:
    build:
      context: ../
      dockerfile: ./zarf/docker/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    # volumes:
    #   - /data:/usr/src/app/data
    environment:
      - GO_SERVICE_DB_CONNECTION_STRING=postgres://postgres:postgres@postgres:5432/go-service
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine3.14
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: go-service
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
